CapaPresentacionTienda/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

using CapaEntidad;
using CapaNegocio;
using CapaEntidad.PayPal;
using CapaPresentacionTienda.Filter;

namespace CapaPresentacionTienda.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DetalleProducto(int idProducto = 0)
        {
            Producto producto = new Producto();
            bool conversion;

            producto = new CapaN_Producto().Listar().Where(p => p.IdProducto == idProducto).FirstOrDefault();
            if(producto != null)
            {     //Utilizo Path para combinar las rutas
                producto.Base64 = CapaNegRecursos.ConvertirBase64(Path.Combine(producto.RutaImagen, producto.NombreImagen), out conversion);
                producto.Extension = Path.GetExtension(producto.NombreImagen);
            }


            return View(producto);
        }

        [HttpGet]
        public JsonResult ListaCategorias()
        {
            List<Categoria> lista = new List<Categoria>();
            lista = new CapaN_Categoria().Listar();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ListarMarcaPorCategoria(int idCategoria)
        {
            List<Marca> lista = new List<Marca>();
            lista = new CapaN_Marca().ListarMarcaPorCategoria(idCategoria);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ListarProducto(int idCategoria,int idMarca)
        {
            List<Producto> lista = new List<Producto>();
            bool conversion;

            lista = new CapaN_Producto().Listar().Select(p => new Producto()
            {
                IdProducto = p.IdProducto,
                Nombre = p.Nombre,
                Descripcion = p.Descripcion,
                ObjMarca = p.ObjMarca,
                ObjCategoria = p.ObjCategoria,
                Precio = p.Precio,
                Stock = p.Stock,
                RutaImagen = p.RutaImagen,
                Base64 = CapaNegRecursos.ConvertirBase64(Path.Combine(p.RutaImagen, p.NombreImagen), out conversion),
                Extension = Path.GetExtension(p.NombreImagen),
                Activo = p.Activo
            }).Where(p =>
            p.ObjCategoria.IdCategoria == (idCategoria == 0 ? p.ObjCategoria.IdCategoria : idCategoria) &&
            p.ObjMarca.IdMarca == (idMarca == 0 ? p.ObjMarca.IdMarca : idMarca) &&
            p.Stock > 0 && p.Activo == true
            ).ToList();

            var jsonResult = Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;

        }
        [HttpPost]

        public JsonResult AgregarAlCarrito(int idproducto)
        {
            //Yo solo quiero el ID del cliente en session,entonces convierto la Session en un objeto Cliente
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool existe = new CapaN_Carrito().ExisteCarrito(idcliente, idproducto);

            bool respuesta = false;
            string mensaje = string.Empty;

            if (existe)
            {
                mensaje = "El producto ya existe en el carrito";    
            }
            else
            {
                respuesta = new CapaN_Carrito().OperacionCarrito(idcliente, idproducto,true, out mensaje);
            }
            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult CantidadEnCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            int cantidad = new CapaN_Carrito().CantidadEnCarrito(idcliente);
            return Json(new { cantidad = cantidad }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ListarProductosCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            List<Carrito> lista = new List<Carrito>();
            bool conversion;

            lista = new CapaN_Carrito().ListarProductos(idcliente).Select(oc => new Carrito()
            {
                ObjProducto = new Producto()
                {
                    IdProducto = oc.ObjProducto.IdProducto,
                    Nombre = oc.ObjProducto.Nombre,
                    ObjMarca = oc.ObjProducto.ObjMarca,
                    Precio = oc.ObjProducto.Precio,
                    RutaImagen = oc.ObjProducto.RutaImagen,
                    Base64 = CapaNegRecursos.ConvertirBase64(Path.Combine(oc.ObjProducto.RutaImagen, oc.ObjProducto.NombreImagen), out conversion),
                    Extension = Path.GetExtension(oc.ObjProducto.NombreImagen)


                },
                Cantidad = oc.Cantidad
            }).ToList();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult OperacionCarrito(int idproducto,bool sumar)
        {
          
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CapaN_Carrito().OperacionCarrito(idcliente, idproducto, sumar, out mensaje);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarCarrito(int idproducto)
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CapaN_Carrito().EliminarCarrito(idcliente, idproducto);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ObtenerProvincia()
        {
            List<Provincia> oLista = new List<Provincia>();

            oLista = new CapaN_Ubicacion().ObtenerProvincia();

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ObtenerCiudad(string IdProvincia)
        {
            List<Ciudad> oLista = new List<Ciudad>();

            oLista = new CapaN_Ubicacion().ObtenerCiudad(IdProvincia);

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }
        [ValidarSession]
        [Authorize]
        public ActionResult Carrito()
        {
            return View();
        }

        [HttpPost]
        //Creo un metodo asíncrono por los servicios de PayPal y creo una tarea (Task)
        public async Task<JsonResult> ProcesarPago(List<Carrito> listaCarrito, Venta oVenta)
        {
            decimal total = 0;
            DataTable detalle_venta = new DataTable();

            detalle_venta.Locale = new CultureInfo("es-AR");
            detalle_venta.Columns.Add("IdProducto", typeof(string));
            detalle_venta.Columns.Add("Cantidad", typeof(int));
            detalle_venta.Columns.Add("Total", typeof(decimal));

            //Creo un alista de elementos
            List<Item> listaItem = new List<Item>();

            foreach(Carrito ObjCarrito in listaCarrito)
            {
                decimal subtotal = Convert.ToDecimal(ObjCarrito.Cantidad.ToString()) * ObjCarrito.ObjProducto.Precio;

                total += subtotal;

                //En la lista voy a guardar todos los productos que esten dentro del carrito
                listaItem.Add(new Item()
                {
                    name = ObjCarrito.ObjProducto.Nombre,
                    quantity = ObjCarrito.Cantidad.ToString(),
                    unit_amount = new UnitAmount()
                    {
                        currency_code = "USD",
                        value = ObjCarrito.ObjProducto.Precio.ToString("G", new CultureInfo("es-AR"))

                    }
                });

                detalle_venta.Rows.Add(new object[]
                {
                    ObjCarrito.ObjProducto.IdProducto,
                    ObjCarrito.Cantidad,
                    subtotal
                });
            }
            PurchaseUnit purchaseUnit = new PurchaseUnit()
            {
                //Le paso el monto total de los precios
                amount = new Amount()
                {
                    currency_code = "USD",
                    value = total.ToString("G", new CultureInfo("es-AR")),
                    //Le paso los mismos valores al breakdown
                    breakdown = new Breakdown()
                    {
                        item_total = new ItemTotal()
                        {
                            currency_code = "USD",
                            value = total.ToString("G", new CultureInfo("es-AR")),
                        }
                    }
                },
                description = "Compra de articulos de Mi Tienda",
                items = listaItem
            };
            Checkout_order checkout_Order = new Checkout_order()
            {
                intent = "CAPTURE",
                purchase_units = new List<PurchaseUnit>() { purchaseUnit },
                application_context = new ApplicationContext()
                {
                    brand_name = "MiTienda.com",
                    landing_page = "NO_PREFERENCE",
                    user_action = "PAY_NOW",
                    return_url = "https://localhost:44369/Tienda/PagoEfectuado",
                    cancel_url = "https://localhost:44369/Tienda/Carrito",

                }
            };
            oVenta.MontoTotal = total;

CapaPresentacionTienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="d-flex flex-column min-vh-100">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid px-4 ">
            <a class="navbar-brand" href="#!">MI TIENDA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","Tienda")">Inicio</a></li>
                    @*<li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>*@
                </ul>
                <form class="d-flex">

                    @if (Session["Cliente"] == null)
                    {
                        <a class="btn btn-outline-dark" aria-current="page" href="@Url.Action("Login","Acceso")"><i class="fas fa-sign-out-alt me-1"></i>Iniciar Sesión</a>
                    }
                    else
                    {
                        <a class="btn btn-outline-dark" href="@Url.Action("Carrito","Tienda")">
                            <i class="fas fa-shopping-cart me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cantidadcarrito">0</span>
                        </a>
                        <ul class="navbar-nav  ms-auto me-0 me-md-3 my-2 my-md-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#!"><b>@User.Identity.Name</b></a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("MisCompras","Tienda")">Mis Compras</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion","Acceso")">Cerrar Sesión</a></li>
                                </ul>
                            </li>
                        </ul>

                    }
                </form>
            </div>
        </div>
    </nav>
    @RenderBody()
    <footer>
        <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>

       //Con este codigo le estoy diciendo que si ha iniciado,va a ejecutar una funcion(La cual es mostrar la cantidad de productos en el carrito)
        $(document).ready(function () {
           MostrarCantidadCarrito();
        })

//Esta function lo que va a hacer es mostrar en la etiqueta del carrito el numero de cosas que se han agregado al carrito,siempre y cuando el cliente inicie sesion.
        function MostrarCantidadCarrito() {

            if ($("#cantidadcarrito").length > 0) {

                 jQuery.ajax({
                    url: "@Url.Action("CantidadEnCarrito", "Tienda")",
                    type: "GET",
                    datatype: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        //cantidad viene del TiendaController mas espesificamente de del metodo CantidadEnCarrito.
                        $("#cantidadcarrito").text(data.cantidad)

                    }

                 })
            }
        }

    </script>
</body>
</html>